name: Vá YouTube Auto
permissions: write-all
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
    inputs:
      retry_count:
        description: 'Do not change value below'
        required: false
        default: '1'

jobs:
  check:
    name: Kiểm tra nguồn vá mới
    runs-on: ubuntu-latest
    strategy:
      matrix:
        patch: [
          "ReVanced/revanced-patches latest youtube-revanced.apk",
          "ReVanced/revanced-patches prerelease youtube-beta-revanced.apk",
          "anddea/revanced-patches latest youtube-stable-anddea.apk",
          "anddea/revanced-patches prerelease youtube-beta-anddea.apk",
          "inotia00/revanced-patches latest youtube-revanced-extended.apk",
          "inotia00/revanced-patches prerelease youtube-beta-revanced-extended.apk",
          "crimera/piko latest twitter-stable-piko.apk",
          "crimera/piko prerelease twitter-beta-piko.apk",
          "kitadai31/revanced-patches-android6-7 latest youtube-revanced-extended-android-6-7.apk",
          "d4n3436/revanced-patches-android5 latest youtube-revanced-extended-android-5.apk",
          "sakarie9/BiliRoamingM latest bilibili-BiliRoamingM.apk",
          "Aunali321/ReVancedExperiments latest telegram-revanced-experiments.apk"
        ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Check patch
        run: |
          org=$(echo ${{ matrix.patch }} | cut -d' ' -f1)
          version=$(echo ${{ matrix.patch }} | cut -d' ' -f2)
          apk_name=$(echo ${{ matrix.patch }} | cut -d' ' -f3)
          echo "Checking patch for $org version $version"
          bash src/etc/ci.sh $org $version $apk_name

  # Các job Patch sẽ được tạo từ các outputs của job check
  Patch-Revanced:
    name: Patch Revanced Stable
    needs: check
    if: ${{ needs.check.outputs.check_rv == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced"

  Patch-Revanced-Beta:
    name: Patch Revanced Beta
    needs: check
    if: ${{ needs.check.outputs.check_rv_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Beta"

  Patch-RVE-anddea-stable:
    name: Patch RVX Anddea Stable
    needs: check
    if: ${{ needs.check.outputs.check_rve_anddea_stable == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "RVE-anddea-stable"

  Patch-RVE-anddea-beta:
    name: Patch RVX Anddea Beta
    needs: check
    if: ${{ needs.check.outputs.check_rve_anddea_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "RVE-anddea-beta"

  Patch-Revanced-Extended:
    name: Patch Revanced Extended
    needs: check
    if: ${{ needs.check.outputs.check_rve == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Extended"

  Patch-Revanced-Extended-Beta:
    name: Patch Revanced Extended Beta
    needs: check
    if: ${{ needs.check.outputs.check_rve_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Extended Beta"

  Patch-Twitter-Piko-Stable:
    name: Patch Twitter Piko Stable
    needs: check
    if: ${{ needs.check.outputs.check_twitter_piko_stable == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Twitter Piko Stable"

  Patch-Twitter-Piko-Beta:
    name: Patch Twitter Piko Beta
    needs: check
    if: ${{ needs.check.outputs.check_twitter_piko_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Twitter Piko Beta"

  Patch-Revanced-Extended-For-Android-6-7:
    name: Patch RVX Android 6 & 7
    needs: check
    if: ${{ needs.check.outputs.check_rve67 == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Extended Android 6,7"

  Patch-Revanced-Extended-For-Android-5:
    name: Patch RVX Android 5
    needs: check
    if: ${{ needs.check.outputs.check_rve5 == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Extended Android 5"

  Patch-BiliRoamingM:
    name: Patch BiliRoamingM
    needs: check
    if: ${{ needs.check.outputs.check_BiliRoamingM == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "BiliRoamingM"

  Patch-Revanced-Experiments:
    name: Patch Revanced Experiments
    needs: check
    if: ${{ needs.check.outputs.check_Revanced_Experiments == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Experiments"
      
