name: Bản Revanced mới hơn
permissions: write-all
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
    inputs:
      retry_count:
        description: 'Do not change value below'
        required: false
        default: '1'
jobs:
  check:
    name: Kiểm tra nguồn vá
    runs-on: ubuntu-latest
    env:
      repository: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Check new patch ReVanced
        id: check-rv
        run: bash src/etc/ci.sh ReVanced/revanced-patches latest youtube-revanced.apk
      - name: Check new patch ReVanced Beta
        id: check-rv-beta
        run: bash src/etc/ci.sh ReVanced/revanced-patches prerelease youtube-beta-revanced.apk
      - name: Check new patch Revanced Extended forked by Anddea Stable Version
        id: check-rve-anddea-stable
        run: bash src/etc/ci.sh anddea/revanced-patches latest youtube-stable-anddea.apk
      - name: Check new patch Revanced Extended forked by Anddea Beta Version
        id: check-rve-anddea-beta
        run: bash src/etc/ci.sh anddea/revanced-patches prerelease youtube-beta-anddea.apk
      - name: Check new patch Revanced Extended
        id: check-rve
        run: bash src/etc/ci.sh inotia00/revanced-patches latest youtube-revanced-extended.apk
      - name: Check new patch Revanced Extended Beta
        id: check-rve-beta
        run: bash src/etc/ci.sh inotia00/revanced-patches prerelease youtube-beta-revanced-extended.apk
      - name: Check new patch Twitter Piko Stable
        id: check-twitter-piko-stable
        run: bash src/etc/ci.sh crimera/piko latest twitter-stable-piko.apk
      - name: Check new patch Twitter Piko Beta
        id: check-twitter-piko-beta
        run: bash src/etc/ci.sh crimera/piko prerelease twitter-beta-piko.apk
      - name: Check new patch Revanced For Android 6 & 7
        id: check-rve67
        run: bash src/etc/ci.sh kitadai31/revanced-patches-android6-7 latest youtube-revanced-extended-android-6-7.apk
      - name: Check new patch Revanced For Android 5
        id: check-rve5
        run: bash src/etc/ci.sh d4n3436/revanced-patches-android5 latest youtube-revanced-extended-android-5.apk
      - name: Check new patch BiliRoamingM
        id: check-BiliRoamingM
        run: bash src/etc/ci.sh sakarie9/BiliRoamingM latest bilibili-BiliRoamingM.apk
      - name: Check new patch Revanced Experiments
        id: check-Revanced-Experiments
        run: bash src/etc/ci.sh Aunali321/ReVancedExperiments latest telegram-revanced-experiments.apk
      - name: Keep workflow run
        uses: gautamkrishnar/keepalive-workflow@v1
    outputs:
      check_rv: ${{ steps.check-rv.outputs.new_patch }}
      check_rv_beta: ${{ steps.check-rv-beta.outputs.new_patch }}
      check_rve_anddea_stable: ${{ steps.check-rve-anddea-stable.outputs.new_patch }}
      check_rve_anddea_beta: ${{ steps.check-rve-anddea-beta.outputs.new_patch }}
      check_rve: ${{ steps.check-rve.outputs.new_patch }}
      check_rve_beta: ${{ steps.check-rve-beta.outputs.new_patch }}
      check_twitter_piko_stable: ${{ steps.check-twitter-piko-stable.outputs.new_patch }}
      check_twitter_piko_beta: ${{ steps.check-twitter-piko-beta.outputs.new_patch }}
      check_rve67: ${{ steps.check-rve67.outputs.new_patch }}
      check_rve5: ${{ steps.check-rve5.outputs.new_patch }}
      check_BiliRoamingM: ${{ steps.check-BiliRoamingM.outputs.new_patch }}
      check_Revanced_Experiments: ${{ steps.check-Revanced-Experiments.outputs.new_patch }}

  Patch-Revanced:
    name: Patch Revanced Stable
    needs: check
    if: ${{ needs.check.outputs.check_rv == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced"
  Patch-Revanced-Beta:
    name: Patch Revanced Beta
    needs: check
    if: ${{ needs.check.outputs.check_rv_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Beta"
  Patch-RVE-anddea-stable:
    name: Patch RVX Anddea Stable
    needs: check
    if: ${{ needs.check.outputs.check_rve_anddea_stable == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "RVE-anddea-stable"
  Patch-RVE-anddea-beta:
    name: Patch RVX Anddea Beta
    needs: check
    if: ${{ needs.check.outputs.check_rve_anddea_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "RVE-anddea-beta"
  Patch-Revanced-Extended:
    name: Patch Revanced Extended
    needs: check
    if: ${{ needs.check.outputs.check_rve == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Extended"
  Patch-Revanced-Extended-Beta:
    name: Patch Revanced Extended Beta
    needs: check
    if: ${{ needs.check.outputs.check_rve_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Extended Beta"
  Patch-Twitter-Piko-Stable:
    name: Patch Twitter Piko Stable
    needs: check
    if: ${{ needs.check.outputs.check_twitter_piko_stable == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Twitter Piko Stable"
  Patch-Twitter-Piko-Beta:
    name: Patch Twitter Piko Beta
    needs: check
    if: ${{ needs.check.outputs.check_twitter_piko_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Twitter Piko Beta"
  Patch-Revanced-Extended-For-Android-6-7:
    name: Patch RVX Android 6 & 7
    needs: check
    if: ${{ needs.check.outputs.check_rve67 == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Extended Android 6,7"
  Patch-Revanced-Extended-For-Android-5:
    name: Patch RVX Android 5
    needs: check
    if: ${{ needs.check.outputs.check_rve5 == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Extended Android 5"
  Patch-BiliRoamingM:
    name: Patch BiliRoamingM
    needs: check
    if: ${{ needs.check.outputs.check_BiliRoamingM == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "BiliRoamingM"
  Patch-Revanced-Experiments:
    name: Patch Revanced Experiments
    needs: check
    if: ${{ needs.check.outputs.check_Revanced_Experiments == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Experiments"
      
